package org.nkey.test.vaadin.view.application.components.user;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;

/**
 * @author m.nikolaev Date: 31.10.12 Time: 2:06
 */
public class Users extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;

    private Table userList = new Table();
    private static String[] visibleCols = new String[]{ "Last Name", "First Name", "Company" };

    /**
     * The constructor should first build the main layout, set the composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the visual editor.
     */
    public Users() {
        buildMainLayout();
        mainLayout.addComponent(userList);


        //userList.setContainerDataSource(addressBookData);
        userList.setVisibleColumns(visibleCols);
        userList.setSelectable(true);
        userList.setImmediate(true);

        setCompositionRoot(mainLayout);

    }



    @AutoGenerated
    private void buildMainLayout() {
        // the main layout and components will be created here
        mainLayout = new AbsoluteLayout();
    }

}
